name: first

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: date

  windows:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        run: date

  macos:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Step one
        run: date

  final:
    name: Fourth job
    runs-on: windows-latest
    needs: [ ubuntu, windows, macos ]
    steps:
      - name: Step one
        run: date